displayingStopwords // in processvars (used by vocabTable)
sortVocabByTopic // in processvars (used by vocabTable)
vocabularyCounts // in processvars (used by mostFrequentWords)
wordTopicCounts // in processvars (used by mostFrequentWords, specificity, addStop, removeStop)
selectedTopic // in processvars (used by mostFrequentWords)
stopwords // in processvars (used by mostFrequentWords, vocabTable, addStop, removeStop)
numTopics // in processvars (used by specificity)
vocabularySize // in processvars (used by addStop, removeStop)
tokensPerTopic // in processvars (used by addStop, removeStop)
documents // in processvars (used by addStop, removeStop)